name: Label PRs
on: [pull_request]
jobs:
    pr-labeler:
        runs-on: ubuntu-latest
        steps:
            -   uses: TimonVS/pr-labeler-action@v3
                if: github.event.action == 'opened'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
